<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CClappy" failures="1" tests="1" name="TestLogin InValidtest" time="6.053" errors="0" timestamp="2025-06-10T15:03:08 IST">
  <testcase classname="test.LoginTest" name="testValidLogin" time="1.81">
    <failure type="java.lang.AssertionError" message="expected [Just a moment...] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at test.LoginTest.testValidLogin(LoginTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
</testsuite> <!-- TestLogin InValidtest -->
